// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetSim.Server.Data;

#nullable disable

namespace PetSim.Server.Migrations
{
    [DbContext(typeof(PetSimContext))]
    [Migration("20250425142340_StatsSeedData")]
    partial class StatsSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PetSim.Server.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PetSim.Server.Models.Stats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Boredom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Happiness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hunger")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("PetSim.Server.Models.StatsAction", b =>
                {
                    b.Property<Guid>("StatsActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StatsActionId");

                    b.ToTable("StatsAction");
                });

            modelBuilder.Entity("PetSim.Server.Models.StatsDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Boredom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Happiness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hunger")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StatsActionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatsDistribution");
                });

            modelBuilder.Entity("PetSim.Server.Models.Stats", b =>
                {
                    b.HasOne("PetSim.Server.Models.Pet", "Pet")
                        .WithOne("Stats")
                        .HasForeignKey("PetSim.Server.Models.Stats", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetSim.Server.Models.StatsAction", b =>
                {
                    b.HasOne("PetSim.Server.Models.StatsDistribution", "StatsDistribution")
                        .WithOne("StatsAction")
                        .HasForeignKey("PetSim.Server.Models.StatsAction", "StatsActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatsDistribution");
                });

            modelBuilder.Entity("PetSim.Server.Models.Pet", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("PetSim.Server.Models.StatsDistribution", b =>
                {
                    b.Navigation("StatsAction")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
