// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetSim.Server.Data;

#nullable disable

namespace PetSim.Server.Migrations
{
    [DbContext(typeof(PetSimContext))]
    [Migration("20250509101659_AddPetAndStatsTables")]
    partial class AddPetAndStatsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetSim.Server.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PetTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PetTypeID");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PetSim.Server.Models.PetStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.ToTable("PetStats");
                });

            modelBuilder.Entity("PetSim.Server.Models.PetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PetTypes");
                });

            modelBuilder.Entity("PetSim.Server.Models.StatsAction", b =>
                {
                    b.Property<Guid>("StatsActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PetTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatsActionId");

                    b.ToTable("StatsAction");
                });

            modelBuilder.Entity("PetSim.Server.Models.StatsDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatsActionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("StatsDistribution");
                });

            modelBuilder.Entity("PetSim.Server.Models.Pet", b =>
                {
                    b.HasOne("PetSim.Server.Models.PetType", "Type")
                        .WithMany()
                        .HasForeignKey("PetTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PetSim.Server.Models.PetStats", b =>
                {
                    b.HasOne("PetSim.Server.Models.Pet", "Pet")
                        .WithOne("Stats")
                        .HasForeignKey("PetSim.Server.Models.PetStats", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PetSim.Server.Models.Stats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("PetStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Boredom")
                                .HasColumnType("int");

                            b1.Property<int>("Happiness")
                                .HasColumnType("int");

                            b1.Property<int>("Hunger")
                                .HasColumnType("int");

                            b1.Property<int>("Loneliness")
                                .HasColumnType("int");

                            b1.Property<int>("Tiredness")
                                .HasColumnType("int");

                            b1.Property<int>("Weight")
                                .HasColumnType("int");

                            b1.HasKey("PetStatsId");

                            b1.ToTable("PetStats");

                            b1.WithOwner()
                                .HasForeignKey("PetStatsId");
                        });

                    b.Navigation("Pet");

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("PetSim.Server.Models.StatsAction", b =>
                {
                    b.HasOne("PetSim.Server.Models.StatsDistribution", "StatsDistribution")
                        .WithOne("StatsAction")
                        .HasForeignKey("PetSim.Server.Models.StatsAction", "StatsActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatsDistribution");
                });

            modelBuilder.Entity("PetSim.Server.Models.StatsDistribution", b =>
                {
                    b.OwnsOne("PetSim.Server.Models.Stats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("StatsDistributionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Boredom")
                                .HasColumnType("int");

                            b1.Property<int>("Happiness")
                                .HasColumnType("int");

                            b1.Property<int>("Hunger")
                                .HasColumnType("int");

                            b1.Property<int>("Loneliness")
                                .HasColumnType("int");

                            b1.Property<int>("Tiredness")
                                .HasColumnType("int");

                            b1.Property<int>("Weight")
                                .HasColumnType("int");

                            b1.HasKey("StatsDistributionId");

                            b1.ToTable("StatsDistribution");

                            b1.WithOwner()
                                .HasForeignKey("StatsDistributionId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("PetSim.Server.Models.Pet", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("PetSim.Server.Models.StatsDistribution", b =>
                {
                    b.Navigation("StatsAction")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
