@PetSim.Server_HostAddress = http://localhost:5210/api
@PetId = 2867b044-e04d-474a-97e8-65fe749380d4

###
GET {{PetSim.Server_HostAddress}}/pet?id={{PetId}}
Content-Type: application/json
Accept: application/json

###
DELETE {{PetSim.Server_HostAddress}}/pet?id={{PetId}}
Content-Type: application/json
Accept: application/json

###
POST {{PetSim.Server_HostAddress}}/pet/
Content-Type: application/json
Accept: application/json

{
  "Name": "Fluffy"
}

###
PUT {{PetSim.Server_HostAddress}}/pet?id={{PetId}}
Content-Type: application/json
Accept: application/json

{
  "Name": "return ov uffy"
}

###
GET {{PetSim.Server_HostAddress}}/stats/{{PetId}}
Content-Type: application/json
Accept: application/json

###
PUT {{PetSim.Server_HostAddress}}/stats?petId={{PetId}}
Content-Type: application/json
Accept: application/json

{
  "Happiness": 100
}