@PetSim.Server_HostAddress = http://localhost:5210/api
@PetId = 5f086c7c-913a-4799-b8a3-d8287480d851

###
GET {{PetSim.Server_HostAddress}}/pet?id={{PetId}}
Content-Type: application/json
Accept: application/json

###
DELETE {{PetSim.Server_HostAddress}}/pet?id={{PetId}}
Content-Type: application/json
Accept: application/json

###
POST {{PetSim.Server_HostAddress}}/pet/
Content-Type: application/json
Accept: application/json

{
  "Name": "Fluffy",
  "Type": "Cat"
}

###
PUT {{PetSim.Server_HostAddress}}/pet?id={{PetId}}
Content-Type: application/json
Accept: application/json

{
  "Name": "return ov uffy"
}

###
GET {{PetSim.Server_HostAddress}}/stats/{{PetId}}
Content-Type: application/json
Accept: application/json

###
PUT {{PetSim.Server_HostAddress}}/stats?petId={{PetId}}
Content-Type: application/json
Accept: application/json

{
  "Happiness": 100
}

###
POST {{PetSim.Server_HostAddress}}/statsAction/action
Content-Type: application/json
Accept: application/json

{
  "Type": "Feed",
  "PetId": "7D65341B-C29F-475E-9AE5-72F54B65761D"
}
